version: "2"
services:
  theta-test-aggregator-db:
    container_name: theta-test-aggregator-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - theta-test-aggregator-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - theta-test-aggregator-db
  theta-test-aggregator:
    container_name: theta-test-aggregator
    environment:
      MAILER_PASSWORD: "${FLUID}"
      MAILER_FROM: "mailtester67@gmail.com"
      MAILER_USER: "mailtester67"
      APIKEY_EXP_DAYS: 30
      APIKEY_EXTENSION_DAYS: 30
      CLIENT_ID: 878632813836-s16kfkrn6i8bahht4asohntr8f695pbc.apps.googleusercontent.com
    build:
      context: ./
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - theta-test-aggregator-db
    volumes:
      - "./:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - theta-test-aggregator
networks:
  inner: {}
volumes:
  theta-test-aggregator-db-data: {}
