import { Injectable } from '@angular/core';
import { Statistic } from '../models/statistic.model';

@Injectable({
  providedIn: 'root'
})
export class StatisticsService {

  constructor() { }

  public statistics: Statistic[] = [
    {
      endpoint: "api/admin/feeschedule",
      method: "POST",
      timeStamp: 1593005699517537213,
      measurement: 365.71839
    },
    {
      endpoint: "api/admin/feeschedule",
      method: "POST",
      timeStamp: 1593020689662105794,
      measurement: 9.037041
    },
    {
      endpoint: "api/admin/feeschedule",
      method: "POST",
      timeStamp: 1593020697071835562,
      measurement: 278.480511
    },
    {
      endpoint: "api/admin/feeschedule",
      method: "POST",
      timeStamp: 1593005700949429767,
      measurement: 318.175751
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onn0/capture",
      method: "GET",
      timeStamp: 1593005699517537213,
      measurement: 40.942237
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onn0/capture",
      method: "GET",
      timeStamp: 1593020689662105794,
      measurement: 10.127263
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onn0/capture",
      method: "GET",
      timeStamp: 1593020697071835562,
      measurement: 7.878517
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onn0/capture",
      method: "GET",
      timeStamp: 1593005700949429767,
      measurement: 322.446506
    },
    {
      endpoint: "api/transaction",
      method: "PUT",
      timeStamp: 1593005699517537213,
      measurement: 8.601592
    },
    {
      endpoint: "api/transaction",
      method: "PUT",
      timeStamp: 1593020689662105794,
      measurement: 42.141745
    },
    {
      endpoint: "api/transaction",
      method: "PUT",
      timeStamp: 1593020697071835562,
      measurement: 42.097079
    },
    {
      endpoint: "api/transaction",
      method: "PUT",
      timeStamp: 1593005700949429767,
      measurement: 34.636815
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onsg/void",
      method: "POST",
      timeStamp: 1593005699517537213,
      measurement: 11.807246
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onsg/void",
      method: "POST",
      timeStamp: 1593020689662105794,
      measurement: 35.241472
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onsg/void",
      method: "POST",
      timeStamp: 1593020697071835562,
      measurement: 36.632
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4onsg/void",
      method: "POST",
      timeStamp: 1593005700949429767,
      measurement: 35.60571
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oohg/capture",
      method: "GET",
      timeStamp: 1593005699517537213,
      measurement: 346.756196
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oohg/capture",
      method: "GET",
      timeStamp: 1593020689662105794,
      measurement: 365.71839
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oohg/capture",
      method: "GET",
      timeStamp: 1593005700949429767,
      measurement: 318.175751
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oohg/capture",
      method: "GET",
      timeStamp: 1593020697071835562,
      measurement: 10.127263
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oomg/refund",
      method: "PUT",
      timeStamp: 1593005699517537213,
      measurement: 425.228186
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oomg/refund",
      method: "PUT",
      timeStamp: 1593020689662105794,
      measurement: 700.878517
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oomg/refund",
      method: "PUT",
      timeStamp: 1593005700949429767,
      measurement: 322.446506
    },
    {
      endpoint: "api/transaction/brpld145t7lvfjg4oomg/refund",
      method: "PUT",
      timeStamp: 1593020697071835562,
      measurement: 42.141745
    }
  ]

  public fetchStatistics(endpoint: string, method: string) {
    return [...this.statistics.filter(s => s.endpoint === endpoint).filter(s => s.method === method)];
  }

  public simulation: Object = {
    stage_1: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/admin/feeschedule',
        request: {
          name: 'Broderick Wehner',
          description: 'Kickstarter intelligentsia put a bird on it lomo meggings XOXO vinyl tumblr 8-bit letterpress.',
          fee_schedule: {
            setup_fee: 1,
            monthly_fees: {
              per_processor_settings: 3559,
              per_device: 0,
              emv: 4500,
              pax_semi: 0,
              rule_engine: 0,
              vault: 0,
              line_items_advanced_fields: 0,
              card_sync: 0
            },
            transaction_fees: {
              auth: 27,
              capture: 26,
              sale: 29,
              'void': 37,
              refund: 35,
              credit: 26,
              signature_capture: 38,
              rule_engine: 31,
              line_items_advanced_fields: 286
            },
            house_ach_fees: {
              application_fee: 31591,
              monthly_fee: 20154,
              sale: 244,
              'void': 101,
              refund: 252,
              credit: 257,
              'return': 10574,
              late_return: 8984,
              large_ticket_amount: 2506689,
              large_ticket_discount_rate_percentage: 77
            },
            third_party_api_fees: {
              verifi: 31,
              domestic_sms: 15
            },
            vault_fees: {
              customer_action: 38,
              payment_method_action: 32,
              address_action: 30
            },
            invoice_fees: {
              create: 11,
              update: 12,
              resend: 20
            },
            device_fees: {
              dejavoo_z11: 179953,
              dejavoo_z6: 213943,
              dejavoo_z1: 243297
            },
            white_label_fee: 5068649,
            terminal_fees: {
              provisioning: 0
            },
            card_sync_fees: {
              application_fee: 0,
              monthly_fee: 0,
              submission: 0,
              match: 0
            }
          }
        },
        response: {
          id: 'brpp25k5t7lmfuaigaqg',
          partner_id: 'FP000000000000000000',
          user_id: 'testadmin11111111111',
          name: 'Broderick Wehner',
          description: 'Kickstarter intelligentsia put a bird on it lomo meggings XOXO vinyl tumblr 8-bit letterpress.',
          fee_schedule: {
            setup_fee: 1,
            monthly_fees: {
              per_processor_settings: 3559,
              per_device: 0,
              emv: 4500,
              pax_semi: 0,
              rule_engine: 0,
              vault: 0,
              line_items_advanced_fields: 0,
              card_sync: 0
            },
            transaction_fees: {
              auth: 27,
              capture: 26,
              sale: 29,
              'void': 37,
              refund: 35,
              credit: 26,
              signature_capture: 38,
              rule_engine: 31,
              line_items_advanced_fields: 286
            },
            house_ach_fees: {
              application_fee: 31591,
              monthly_fee: 20154,
              sale: 244,
              'void': 101,
              refund: 252,
              credit: 257,
              'return': 10574,
              late_return: 8984,
              large_ticket_amount: 2506689,
              large_ticket_discount_rate_percentage: 77
            },
            third_party_api_fees: {
              verifi: 31,
              domestic_sms: 15
            },
            vault_fees: {
              customer_action: 38,
              payment_method_action: 32,
              address_action: 30
            },
            invoice_fees: {
              create: 11,
              update: 12,
              resend: 20
            },
            device_fees: {
              dejavoo_z11: 179953,
              dejavoo_z6: 213943,
              dejavoo_z1: 243297
            },
            white_label_fee: 5068649,
            terminal_fees: {
              provisioning: 0
            },
            card_sync_fees: {
              application_fee: 0,
              monthly_fee: 0,
              submission: 0,
              match: 0
            }
          }
        },
        failed_message: '',
        measurement: '9.037041ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/partner',
        request: {
          sales_user_id: null,
          type: null,
          name: 'Velva Schneider',
          description: 'empower',
          website: 'investormaximize.biz',
          email: 'deekunde@tillman.io',
          fee_schedule_id: 'brpp25k5t7lmfuaigaqg',
          primary_contact: {
            first_name: 'Zion',
            last_name: 'Heathcote',
            company: 'Langworth-Nicolas',
            address_line_1: '2550 Manorport',
            address_line_2: null,
            city: 'Franciscahaven',
            state: 'FL',
            postal_code: '60185',
            country: 'US',
            phone: '9651236391',
            phone_ext: null,
            fax: null,
            email: 'wilburnhalvorson@schaden.name'
          },
          billing_contact: {
            first_name: 'Lorna',
            last_name: 'Leannon',
            company: 'Crooks, Yost and Rippin',
            address_line_1: '293 Parkwaysfort',
            address_line_2: null,
            city: 'Macstad',
            state: 'MH',
            postal_code: '60185',
            country: 'US',
            phone: '1867799694',
            phone_ext: null,
            fax: null,
            email: 'lelabeier@sipes.org'
          },
          risk_contact: {
            first_name: 'Stacey',
            last_name: 'Schmidt',
            company: 'McClure Inc',
            address_line_1: '4383 Port Centerschester',
            address_line_2: null,
            city: 'Alvinaton',
            state: 'WA',
            postal_code: '60185',
            country: 'US',
            phone: '6996103275',
            phone_ext: null,
            fax: null,
            email: 'melyssakuhic@blanda.net'
          },
          support_contact: {
            first_name: 'Demetrius',
            last_name: 'Jacobi',
            company: 'Larkin, Schamberger and Torphy',
            address_line_1: '66157 Isleside',
            address_line_2: null,
            city: 'Emmerichport',
            state: 'AR',
            postal_code: '60185',
            country: 'US',
            phone: '4042672690',
            phone_ext: null,
            fax: null,
            email: 'vernerbergnaum@nader.org'
          },
          billing: {
            ach: {
              type: 'ccd',
              routing_number: '490000018',
              account_number: '284919',
              masked_account_number: '',
              account_type: 'checking'
            }
          },
          user: {
            username: 'Sauer5926',
            name: 'Johann Upton',
            phone: '4336686442',
            email: 'scarlettsatterfield@watsica.com',
            password: 'Test_partner_1!',
            status: 'active',
            role: 'admin',
            send_welcome: false
          }
        },
        response: {
          id: 'brpp25k5t7lmfuaigar0',
          parent_id: '',
          type: 'gateway',
          name: 'Velva Schneider',
          description: 'empower',
          website: 'investormaximize.biz',
          status: 'pending_tos',
          email: 'deekunde@tillman.io',
          fee_schedule_id: 'brpp25k5t7lmfuaigaqg',
          primary_contact: {
            first_name: 'Zion',
            last_name: 'Heathcote',
            company: 'Langworth-Nicolas',
            address_line_1: '2550 Manorport',
            address_line_2: '',
            city: 'Franciscahaven',
            state: 'FL',
            postal_code: '60185',
            country: 'US',
            phone: '9651236391',
            phone_ext: '',
            fax: '',
            email: 'wilburnhalvorson@schaden.name'
          },
          billing_contact: {
            first_name: 'Lorna',
            last_name: 'Leannon',
            company: 'Crooks, Yost and Rippin',
            address_line_1: '293 Parkwaysfort',
            address_line_2: '',
            city: 'Macstad',
            state: 'MH',
            postal_code: '60185',
            country: 'US',
            phone: '1867799694',
            phone_ext: '',
            fax: '',
            email: 'lelabeier@sipes.org'
          },
          risk_contact: {
            first_name: 'Stacey',
            last_name: 'Schmidt',
            company: 'McClure Inc',
            address_line_1: '4383 Port Centerschester',
            address_line_2: '',
            city: 'Alvinaton',
            state: 'WA',
            postal_code: '60185',
            country: 'US',
            phone: '6996103275',
            phone_ext: '',
            fax: '',
            email: 'melyssakuhic@blanda.net'
          },
          support_contact: {
            first_name: 'Demetrius',
            last_name: 'Jacobi',
            company: 'Larkin, Schamberger and Torphy',
            address_line_1: '66157 Isleside',
            address_line_2: '',
            city: 'Emmerichport',
            state: 'AR',
            postal_code: '60185',
            country: 'US',
            phone: '4042672690',
            phone_ext: '',
            fax: '',
            email: 'vernerbergnaum@nader.org'
          },
          permissions: {
            create_sub_partners: true,
            create_sub_merchants: true
          },
          billing: {
            ach: {
              type: 'ccd',
              routing_number: '490000018',
              masked_account_number: '28**19',
              account_type: 'checking'
            }
          },
          stats: {
            direct_merchants: 0,
            indirect_merchants: 0,
            direct_partners: 0,
            indirect_partners: 0
          },
          available_processors: [
            'all'
          ],
          tos_accepted_by: '',
          tos_accepted_by_username: '',
          created_at: '2020-06-24T17:44:54.884039834Z',
          tos_last_accepted_at: null
        },
        failed_message: '',
        measurement: '278.480511ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/token-auth',
        request: {
          auth_key: null,
          username: 'Sauer5926',
          password: 'Test_partner_1!',
          totp: ''
        },
        response: {
          token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTMxMDcwOTUsImlhdCI6MTU5MzAyMDY5NSwianRpIjoiYmIzODc4YmUtYThiYi00NDhiLTk1YTEtOWRhMjcyMmEyZjIyIiwibmFtZSI6IkpvaGFubiBVcHRvbiIsIm5iZiI6MTU5MzAyMDY5NSwicm9sZSI6ImFkbWluIiwic2lkIjoiY2I2YTczOWQtMGZmZi00YThlLTliMTgtYjljYzIxMWY5NjlhIiwidGlkIjoiYnJwcDI1azV0N2xtZnVhaWdhcjAiLCJ1aWQiOiJicnBwMjVrNXQ3bG1mdWFpZ2FyZyIsInVzZXJuYW1lIjoic2F1ZXI1OTI2IiwidXQiOiJwYXJ0bmVyIn0.UzmRgsjvU53BmwticPd3C4uxMrhqioB8aA0Sxd05Pv8',
          sid: 'cb6a739d-0fff-4a8e-9b18-b9cc211f969a'
        },
        failed_message: '',
        measurement: '318.175751ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/accept-tos',
        request: {
          name: 'Velva Schneider',
          title: 'mx',
          account_type: null,
          account_type_id: null
        },
        response: {
          status: 'success',
          msg: 'success'
        },
        failed_message: '',
        measurement: '10.127263ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/user/apikey',
        request: {
          type: 'api',
          name: 'Ottis Anderson'
        },
        response: {
          api_key: 'api_1dmC5DHEKPQckuc0TU63GnHnL9Q'
        },
        failed_message: '',
        measurement: '7.878517ms',
        status_code: 200
      }
    ],
    stage_10: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'PHP',
          description: 'Raw denim twee banh mi.',
          order_id: 'Innovative',
          po_number: 'analyzer',
          ip_address: '240.255.113.143',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 3641,
          tax_amount: 41,
          shipping_amount: 91,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            token: null,
            apm: {
              type: 'dragonpay',
              selling_point: null,
              sold_service: null,
              merchant_redirect_url: 'http://pe-test.dev.fluidpay.com:8127/readlog',
              locale: null,
              mobile_view: false,
              national_id: null,
              consumer_ref: null
            }
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Ophelia',
            last_name: 'Bode',
            company: 'Moen-Mertz',
            address_line_1: '87968 Unionfort',
            address_line_2: null,
            city: 'Howetown',
            state: 'PW',
            postal_code: '0185',
            country: 'PH',
            phone: '8498060558',
            fax: null,
            email: 'jarrettboyer@kirlin.net'
          },
          shipping_address: {
            first_name: 'Wilford',
            last_name: 'Vandervort',
            company: 'Boyle Inc',
            address_line_1: '81175 Highwaytown',
            address_line_2: null,
            city: 'North Treutel',
            state: 'UT',
            postal_code: '60185',
            country: 'US',
            phone: '3021680805',
            fax: null,
            email: 'brooklynbarrows@eichmann.io'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp2645t7lmfuaigc10',
          user_id: 'brpp24s5t7lmfuaiga60',
          user_name: 'walsh4936',
          merchant_id: 'brpp24s5t7lmfuaiga5g',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 3641,
          base_amount: 18446744073709402000,
          amount_authorized: 0,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 153840,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga80',
          processor_type: 'mgiapm',
          processor_name: 'Ivy Welch',
          payment_method: 'apm',
          payment_type: 'dragonpay',
          features: [
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 41,
          tax_exempt: false,
          shipping_amount: 91,
          surcharge: 0,
          discount_amount: 0,
          currency: 'php',
          description: 'Raw denim twee banh mi.',
          order_id: 'Innovative',
          po_number: 'analyzer',
          ip_address: '240.255.113.143',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: '',
          customer_payment_type: '',
          customer_payment_ID: '',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            apm: {
              status: 'failed',
              processor_transaction_id: '688868241',
              transaction_id: 'brpp2645t7lmfuaigc10',
              funding_status: 'not_expected',
              redirect_url: 'http://localhost:8080//api/redirect/apm/brpp2645t7lmfuaigc1g',
              channel: 'testchannel',
              tag: 'dragonpay',
              document_code: ''
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'declined',
          response: 'declined',
          response_code: 400,
          billing_address: {
            first_name: 'Ophelia',
            last_name: 'Bode',
            company: 'Moen-Mertz',
            address_line_1: '87968 Unionfort',
            address_line_2: '',
            city: 'Howetown',
            state: 'PW',
            postal_code: '0185',
            country: 'PH',
            phone: '8498060558',
            fax: '',
            email: 'jarrettboyer@kirlin.net'
          },
          shipping_address: {
            first_name: 'Wilford',
            last_name: 'Vandervort',
            company: 'Boyle Inc',
            address_line_1: '81175 Highwaytown',
            address_line_2: '',
            city: 'North Treutel',
            state: 'UT',
            postal_code: '60185',
            country: 'US',
            phone: '3021680805',
            fax: '',
            email: 'brooklynbarrows@eichmann.io'
          },
          created_at: '2020-06-24T17:44:56.434388863Z',
          updated_at: '2020-06-24T17:44:56.745343104Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: '',
        measurement: '322.446506ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: ' http://localhost:8001/api',
        request: null,
        response: 'due to compatibility issues we cannot return the transaction here',
        failed_message: 'TransactionSettleAuth failed, status isn\'t \'settled\'',
        measurement: '',
        status_code: 0
      }
    ],
    stage_11: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'PHP',
          description: 'Street lomo park.',
          order_id: 'client-driven',
          po_number: 'internet solution',
          ip_address: '186.225.9.43',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 4414,
          tax_amount: 1,
          shipping_amount: 5,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            token: null,
            apm: {
              type: 'dragonpay',
              selling_point: null,
              sold_service: null,
              merchant_redirect_url: 'http://pe-test.dev.fluidpay.com:8127/readlog',
              locale: null,
              mobile_view: false,
              national_id: null,
              consumer_ref: null
            }
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Tyra',
            last_name: 'Bins',
            company: 'Zemlak-Rosenbaum',
            address_line_1: '841 West Missionton',
            address_line_2: null,
            city: 'West Zieme',
            state: 'GU',
            postal_code: '0185',
            country: 'PH',
            phone: '4118166329',
            fax: null,
            email: 'lucyvolkman@price.net'
          },
          shipping_address: {
            first_name: 'Lisette',
            last_name: 'Bashirian',
            company: 'Nikolaus, Shanahan and Armstrong',
            address_line_1: '3623 Crescentmouth',
            address_line_2: null,
            city: 'New Kuhic',
            state: 'MI',
            postal_code: '60185',
            country: 'US',
            phone: '8502269336',
            fax: null,
            email: 'hazlecormier@harvey.com'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp2645t7lmfuaigc30',
          user_id: 'brpp24s5t7lmfuaiga60',
          user_name: 'walsh4936',
          merchant_id: 'brpp24s5t7lmfuaiga5g',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 4414,
          base_amount: 18446744073709402000,
          amount_authorized: 0,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 153840,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga80',
          processor_type: 'mgiapm',
          processor_name: 'Ivy Welch',
          payment_method: 'apm',
          payment_type: 'dragonpay',
          features: [
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 1,
          tax_exempt: false,
          shipping_amount: 5,
          surcharge: 0,
          discount_amount: 0,
          currency: 'php',
          description: 'Street lomo park.',
          order_id: 'client-driven',
          po_number: 'internet solution',
          ip_address: '186.225.9.43',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: '',
          customer_payment_type: '',
          customer_payment_ID: '',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            apm: {
              status: 'failed',
              processor_transaction_id: '690977011',
              transaction_id: 'brpp2645t7lmfuaigc30',
              funding_status: 'not_expected',
              redirect_url: 'http://localhost:8080//api/redirect/apm/brpp2645t7lmfuaigc3g',
              channel: 'testchannel',
              tag: 'dragonpay',
              document_code: ''
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'declined',
          response: 'declined',
          response_code: 400,
          billing_address: {
            first_name: 'Tyra',
            last_name: 'Bins',
            company: 'Zemlak-Rosenbaum',
            address_line_1: '841 West Missionton',
            address_line_2: '',
            city: 'West Zieme',
            state: 'GU',
            postal_code: '0185',
            country: 'PH',
            phone: '4118166329',
            fax: '',
            email: 'lucyvolkman@price.net'
          },
          shipping_address: {
            first_name: 'Lisette',
            last_name: 'Bashirian',
            company: 'Nikolaus, Shanahan and Armstrong',
            address_line_1: '3623 Crescentmouth',
            address_line_2: '',
            city: 'New Kuhic',
            state: 'MI',
            postal_code: '60185',
            country: 'US',
            phone: '8502269336',
            fax: '',
            email: 'hazlecormier@harvey.com'
          },
          created_at: '2020-06-24T17:44:56.764622121Z',
          updated_at: '2020-06-24T17:44:57.029967394Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: '',
        measurement: '285.212997ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: ' http://localhost:8001/api',
        request: null,
        response: 'due to compatibility issues we cannot return the transaction here',
        failed_message: 'TransactionSettleAuth failed, status isn\'t \'settled\'',
        measurement: '',
        status_code: 0
      }
    ],
    stage_2: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'authorize',
          tax_exempt: false,
          currency: 'USD',
          description: '90\'s farm-to-table sustainable.',
          order_id: 'Isabel',
          po_number: 'Aaliyah',
          ip_address: '177.132.184.162',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 2635,
          tax_amount: 45,
          shipping_amount: 1,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '476',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Christop',
            last_name: 'Mohr',
            company: 'Kuhlman Group',
            address_line_1: '2542 South Dalechester',
            address_line_2: null,
            city: 'Spencerside',
            state: 'OK',
            postal_code: '60185',
            country: 'US',
            phone: '4667233021',
            fax: null,
            email: 'zanewitting@schuster.biz'
          },
          shipping_address: {
            first_name: 'Brooklyn',
            last_name: 'Okuneva',
            company: 'Ortiz, Wiza and Hegmann',
            address_line_1: '2392 West Avenueside',
            address_line_2: null,
            city: 'Lake Franecki',
            state: 'DC',
            postal_code: '60185',
            country: 'US',
            phone: '9955238872',
            fax: null,
            email: 'andrewbrakus@bergnaum.name'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigat0',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'authorize',
          amount: 2635,
          base_amount: 18446744073708857000,
          amount_authorized: 2635,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 45,
          tax_exempt: false,
          shipping_amount: 1,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: '90\'s farm-to-table sustainable.',
          order_id: 'Isabel',
          po_number: 'Aaliyah',
          ip_address: '177.132.184.162',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigb0g',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp25s5t7lmfuaigb00',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigatg',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.506787906Z',
              updated_at: '2020-06-24T17:44:55.517073016Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'authorized',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Christop',
            last_name: 'Mohr',
            company: 'Kuhlman Group',
            address_line_1: '2542 South Dalechester',
            address_line_2: '',
            city: 'Spencerside',
            state: 'OK',
            postal_code: '60185',
            country: 'US',
            phone: '4667233021',
            fax: '',
            email: 'zanewitting@schuster.biz'
          },
          shipping_address: {
            first_name: 'Brooklyn',
            last_name: 'Okuneva',
            company: 'Ortiz, Wiza and Hegmann',
            address_line_1: '2392 West Avenueside',
            address_line_2: '',
            city: 'Lake Franecki',
            state: 'DC',
            postal_code: '60185',
            country: 'US',
            phone: '9955238872',
            fax: '',
            email: 'andrewbrakus@bergnaum.name'
          },
          created_at: '2020-06-24T17:44:55.501077805Z',
          updated_at: '2020-06-24T17:44:55.51998265Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: 'TransactionCreateAuth failed, amounts are different',
        measurement: '42.141745ms',
        status_code: 200
      }
    ],
    stage_3: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'USD',
          description: 'Venmo gluten-free lo-fi.',
          order_id: 'bicycle rights',
          po_number: 'stumptown',
          ip_address: '210.164.247.172',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 4229,
          tax_amount: 56,
          shipping_amount: 64,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '483',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Cecilia',
            last_name: 'Bayer',
            company: 'Morar, Miller and Hickle',
            address_line_1: '899 New Keymouth',
            address_line_2: null,
            city: 'New Thiel',
            state: 'MH',
            postal_code: '60185',
            country: 'US',
            phone: '4463592138',
            fax: null,
            email: 'jaylenbaumbach@heaney.biz'
          },
          shipping_address: {
            first_name: 'Isabel',
            last_name: 'Dooley',
            company: 'Smitham, Rempel and Casper',
            address_line_1: '9642 Inletfurt',
            address_line_2: null,
            city: 'North Kuhic',
            state: 'NC',
            postal_code: '60185',
            country: 'US',
            phone: '5081847699',
            fax: null,
            email: 'noelmaggio@denesik.biz'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigb1g',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 4229,
          base_amount: 18446744073708860000,
          amount_authorized: 4229,
          amount_captured: 4229,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 56,
          tax_exempt: false,
          shipping_amount: 64,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Venmo gluten-free lo-fi.',
          order_id: 'bicycle rights',
          po_number: 'stumptown',
          ip_address: '210.164.247.172',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigb50',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp25s5t7lmfuaigb4g',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigb20',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.557642494Z',
              updated_at: '2020-06-24T17:44:55.567946847Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'pending_settlement',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Cecilia',
            last_name: 'Bayer',
            company: 'Morar, Miller and Hickle',
            address_line_1: '899 New Keymouth',
            address_line_2: '',
            city: 'New Thiel',
            state: 'MH',
            postal_code: '60185',
            country: 'US',
            phone: '4463592138',
            fax: '',
            email: 'jaylenbaumbach@heaney.biz'
          },
          shipping_address: {
            first_name: 'Isabel',
            last_name: 'Dooley',
            company: 'Smitham, Rempel and Casper',
            address_line_1: '9642 Inletfurt',
            address_line_2: '',
            city: 'North Kuhic',
            state: 'NC',
            postal_code: '60185',
            country: 'US',
            phone: '5081847699',
            fax: '',
            email: 'noelmaggio@denesik.biz'
          },
          created_at: '2020-06-24T17:44:55.546202914Z',
          updated_at: '2020-06-24T17:44:55.570437168Z',
          captured_at: '2020-06-24T17:44:55.570436691Z',
          settled_at: null
        },
        failed_message: '',
        measurement: '42.097079ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction/brpp25s5t7lmfuaigb1g/void',
        request: null,
        response: {
          status: 'success',
          msg: 'success'
        },
        failed_message: '',
        measurement: '11.177348ms',
        status_code: 200
      }
    ],
    stage_4: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'USD',
          description: 'Echo truffaut asymmetrical.',
          order_id: 'polaroid',
          po_number: 'stumptown',
          ip_address: '186.186.29.53',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 3283,
          tax_amount: 46,
          shipping_amount: 63,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '143',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Eliezer',
            last_name: 'Effertz',
            company: 'Predovic, Hettinger and Schaden',
            address_line_1: '933 Stationchester',
            address_line_2: null,
            city: 'Croninside',
            state: 'AZ',
            postal_code: '60185',
            country: 'US',
            phone: '4287735671',
            fax: null,
            email: 'lelamohr@fadel.info'
          },
          shipping_address: {
            first_name: 'Eldred',
            last_name: 'Mraz',
            company: 'Wyman, Marvin and Metz',
            address_line_1: '7723 New Spurland',
            address_line_2: null,
            city: 'Port Deckow',
            state: 'MA',
            postal_code: '60185',
            country: 'US',
            phone: '5150966569',
            fax: null,
            email: 'juniorkoelpin@crist.net'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigb6g',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 3283,
          base_amount: 18446744073708857000,
          amount_authorized: 3283,
          amount_captured: 3283,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 46,
          tax_exempt: false,
          shipping_amount: 63,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Echo truffaut asymmetrical.',
          order_id: 'polaroid',
          po_number: 'stumptown',
          ip_address: '186.186.29.53',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigba0',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp25s5t7lmfuaigb9g',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigb70',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.603362369Z',
              updated_at: '2020-06-24T17:44:55.613504667Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'pending_settlement',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Eliezer',
            last_name: 'Effertz',
            company: 'Predovic, Hettinger and Schaden',
            address_line_1: '933 Stationchester',
            address_line_2: '',
            city: 'Croninside',
            state: 'AZ',
            postal_code: '60185',
            country: 'US',
            phone: '4287735671',
            fax: '',
            email: 'lelamohr@fadel.info'
          },
          shipping_address: {
            first_name: 'Eldred',
            last_name: 'Mraz',
            company: 'Wyman, Marvin and Metz',
            address_line_1: '7723 New Spurland',
            address_line_2: '',
            city: 'Port Deckow',
            state: 'MA',
            postal_code: '60185',
            country: 'US',
            phone: '5150966569',
            fax: '',
            email: 'juniorkoelpin@crist.net'
          },
          created_at: '2020-06-24T17:44:55.597300583Z',
          updated_at: '2020-06-24T17:44:55.616389563Z',
          captured_at: '2020-06-24T17:44:55.616389472Z',
          settled_at: null
        },
        failed_message: '',
        measurement: '36.707182ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: ' http://localhost:8001/api',
        request: null,
        response: 'due to compatibility issues we cannot return the transaction here',
        failed_message: '',
        measurement: '',
        status_code: 0
      }
    ],
    stage_5: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'USD',
          description: 'Fanny pack venmo tilde.',
          order_id: 'photo booth',
          po_number: 'hoodie',
          ip_address: '168.224.175.136',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 9926,
          tax_amount: 85,
          shipping_amount: 78,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '795',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Ignatius',
            last_name: 'Bergstrom',
            company: 'Schmitt Inc',
            address_line_1: '171 East Plazafurt',
            address_line_2: null,
            city: 'Goodwinmouth',
            state: 'SD',
            postal_code: '60185',
            country: 'US',
            phone: '4465542121',
            fax: null,
            email: 'kevincremin@murphy.biz'
          },
          shipping_address: {
            first_name: 'Bettye',
            last_name: 'Crona',
            company: 'Goyette, Gutmann and Greenholt',
            address_line_1: '9577 East Centersland',
            address_line_2: null,
            city: 'Oswaldbury',
            state: 'SC',
            postal_code: '60185',
            country: 'US',
            phone: '2839309170',
            fax: null,
            email: 'kipschmeler@effertz.io'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigbb0',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 9926,
          base_amount: 18446744073708866000,
          amount_authorized: 9926,
          amount_captured: 9926,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 85,
          tax_exempt: false,
          shipping_amount: 78,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Fanny pack venmo tilde.',
          order_id: 'photo booth',
          po_number: 'hoodie',
          ip_address: '168.224.175.136',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigbeg',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp25s5t7lmfuaigbe0',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigbbg',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.794222825Z',
              updated_at: '2020-06-24T17:44:55.817496907Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'pending_settlement',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Ignatius',
            last_name: 'Bergstrom',
            company: 'Schmitt Inc',
            address_line_1: '171 East Plazafurt',
            address_line_2: '',
            city: 'Goodwinmouth',
            state: 'SD',
            postal_code: '60185',
            country: 'US',
            phone: '4465542121',
            fax: '',
            email: 'kevincremin@murphy.biz'
          },
          shipping_address: {
            first_name: 'Bettye',
            last_name: 'Crona',
            company: 'Goyette, Gutmann and Greenholt',
            address_line_1: '9577 East Centersland',
            address_line_2: '',
            city: 'Oswaldbury',
            state: 'SC',
            postal_code: '60185',
            country: 'US',
            phone: '2839309170',
            fax: '',
            email: 'kipschmeler@effertz.io'
          },
          created_at: '2020-06-24T17:44:55.778804063Z',
          updated_at: '2020-06-24T17:44:55.823513782Z',
          captured_at: '2020-06-24T17:44:55.823513284Z',
          settled_at: null
        },
        failed_message: '',
        measurement: '117.065746ms',
        status_code: 200
      },
      {
        error: null,
        endpoint: ' http://localhost:8001/api',
        request: null,
        response: 'due to compatibility issues we cannot return the transaction here',
        failed_message: '',
        measurement: '',
        status_code: 0
      },
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction/brpp25s5t7lmfuaigbb0/refund',
        request: {
          amount: null,
          ip_address: '168.224.175.136',
          terminal_id: null,
          vendor_id: null,
          print_receipt: null,
          signature_required: false
        },
        response: {
          id: 'brpp25s5t7lmfuaigbfg',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'refund',
          amount: 9926,
          base_amount: 18446744073708866000,
          amount_authorized: 9926,
          amount_captured: 9926,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'fake_response'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 0,
          tax_exempt: false,
          shipping_amount: 0,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: '',
          order_id: 'photo booth',
          po_number: '',
          ip_address: '168.224.175.136',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigbeg',
          customer_payment_type: '',
          customer_payment_ID: '',
          subscription_id: '',
          referenced_transaction_id: 'brpp25s5t7lmfuaigbb0',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigbg0',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'pending',
              response_code: 100,
              auth_code: '123456',
              processor_response_code: '00',
              processor_response_text: 'PENDING',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: '0',
              cvv_response_code: '',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.934237145Z',
              updated_at: '2020-06-24T17:44:55.942325074Z'
            }
          },
          custom_fields: null,
          line_items: null,
          status: 'pending_settlement',
          response: 'pending',
          response_code: 100,
          billing_address: {
            first_name: 'Ignatius',
            last_name: 'Bergstrom',
            company: 'Schmitt Inc',
            address_line_1: '171 East Plazafurt',
            address_line_2: '',
            city: 'Goodwinmouth',
            state: 'SD',
            postal_code: '60185',
            country: 'US',
            phone: '4465542121',
            fax: '',
            email: 'kevincremin@murphy.biz'
          },
          shipping_address: {
            first_name: 'Bettye',
            last_name: 'Crona',
            company: 'Goyette, Gutmann and Greenholt',
            address_line_1: '9577 East Centersland',
            address_line_2: '',
            city: 'Oswaldbury',
            state: 'SC',
            postal_code: '60185',
            country: 'US',
            phone: '2839309170',
            fax: '',
            email: 'kipschmeler@effertz.io'
          },
          created_at: '2020-06-24T17:44:55.925577137Z',
          updated_at: '2020-06-24T17:44:55.945249783Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: '',
        measurement: '34.636815ms',
        status_code: 200
      }
    ],
    stage_6: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'authorize',
          tax_exempt: false,
          currency: 'USD',
          description: 'Marfa normcore pickled.',
          order_id: 'Ebba',
          po_number: 'Cloyd',
          ip_address: '227.149.189.223',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 4954,
          tax_amount: 43,
          shipping_amount: 60,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '518',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Noelia',
            last_name: 'Casper',
            company: 'Jast LLC',
            address_line_1: '7036 Capestad',
            address_line_2: null,
            city: 'Pourosfurt',
            state: 'TN',
            postal_code: '60185',
            country: 'US',
            phone: '9691158076',
            fax: null,
            email: 'bobbyjenkins@lockman.info'
          },
          shipping_address: {
            first_name: 'Austen',
            last_name: 'Yundt',
            company: 'Kemmer-Ledner',
            address_line_1: '36866 Glentown',
            address_line_2: null,
            city: 'Hoegerview',
            state: 'SC',
            postal_code: '60185',
            country: 'US',
            phone: '6916854211',
            fax: null,
            email: 'makennarunolfsdottir@bernhard.name'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigbhg',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'authorize',
          amount: 4954,
          base_amount: 18446744073708860000,
          amount_authorized: 4954,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 43,
          tax_exempt: false,
          shipping_amount: 60,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Marfa normcore pickled.',
          order_id: 'Ebba',
          po_number: 'Cloyd',
          ip_address: '227.149.189.223',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp25s5t7lmfuaigbl0',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp25s5t7lmfuaigbkg',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp25s5t7lmfuaigbi0',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:55.965590464Z',
              updated_at: '2020-06-24T17:44:55.975055156Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'authorized',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Noelia',
            last_name: 'Casper',
            company: 'Jast LLC',
            address_line_1: '7036 Capestad',
            address_line_2: '',
            city: 'Pourosfurt',
            state: 'TN',
            postal_code: '60185',
            country: 'US',
            phone: '9691158076',
            fax: '',
            email: 'bobbyjenkins@lockman.info'
          },
          shipping_address: {
            first_name: 'Austen',
            last_name: 'Yundt',
            company: 'Kemmer-Ledner',
            address_line_1: '36866 Glentown',
            address_line_2: '',
            city: 'Hoegerview',
            state: 'SC',
            postal_code: '60185',
            country: 'US',
            phone: '6916854211',
            fax: '',
            email: 'makennarunolfsdottir@bernhard.name'
          },
          created_at: '2020-06-24T17:44:55.959326473Z',
          updated_at: '2020-06-24T17:44:55.977800446Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: 'TransactionCreateAuth failed, amounts are different',
        measurement: '35.241472ms',
        status_code: 200
      }
    ],
    stage_7: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'authorize',
          tax_exempt: false,
          currency: 'USD',
          description: 'Cleanse kitsch kombucha.',
          order_id: 'Blake',
          po_number: 'Danial',
          ip_address: '71.66.4.66',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 6226,
          tax_amount: 41,
          shipping_amount: 16,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '724',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Columbus',
            last_name: 'Thiel',
            company: 'Lubowitz, Prohaska and Mitchell',
            address_line_1: '762 West Millsberg',
            address_line_2: null,
            city: 'Lake Stroman',
            state: 'NJ',
            postal_code: '60185',
            country: 'US',
            phone: '7676845856',
            fax: null,
            email: 'nicholausturcotte@runolfsson.name'
          },
          shipping_address: {
            first_name: 'Hallie',
            last_name: 'Gutmann',
            company: 'Stracke, Hartmann and Tremblay',
            address_line_1: '47409 Hollowberg',
            address_line_2: null,
            city: 'New Leuschke',
            state: 'IN',
            postal_code: '60185',
            country: 'US',
            phone: '7512058850',
            fax: null,
            email: 'davewisozk@lindgren.com'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp25s5t7lmfuaigbm0',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'authorize',
          amount: 6226,
          base_amount: 18446744073708861000,
          amount_authorized: 6226,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 41,
          tax_exempt: false,
          shipping_amount: 16,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Cleanse kitsch kombucha.',
          order_id: 'Blake',
          po_number: 'Danial',
          ip_address: '71.66.4.66',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp2645t7lmfuaigbpg',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp2645t7lmfuaigbp0',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp2645t7lmfuaigbmg',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:56.000417899Z',
              updated_at: '2020-06-24T17:44:56.009604698Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'authorized',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Columbus',
            last_name: 'Thiel',
            company: 'Lubowitz, Prohaska and Mitchell',
            address_line_1: '762 West Millsberg',
            address_line_2: '',
            city: 'Lake Stroman',
            state: 'NJ',
            postal_code: '60185',
            country: 'US',
            phone: '7676845856',
            fax: '',
            email: 'nicholausturcotte@runolfsson.name'
          },
          shipping_address: {
            first_name: 'Hallie',
            last_name: 'Gutmann',
            company: 'Stracke, Hartmann and Tremblay',
            address_line_1: '47409 Hollowberg',
            address_line_2: '',
            city: 'New Leuschke',
            state: 'IN',
            postal_code: '60185',
            country: 'US',
            phone: '7512058850',
            fax: '',
            email: 'davewisozk@lindgren.com'
          },
          created_at: '2020-06-24T17:44:55.994672115Z',
          updated_at: '2020-06-24T17:44:56.012502826Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: 'TransactionCreateAuth failed, amounts are different',
        measurement: '36.632ms',
        status_code: 200
      }
    ],
    stage_8: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'authorize',
          tax_exempt: false,
          currency: 'USD',
          description: 'Keffiyeh street kickstarter.',
          order_id: 'Katrine',
          po_number: 'Hildegard',
          ip_address: '232.182.219.16',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 9173,
          tax_amount: 59,
          shipping_amount: 7,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            card: {
              entry_type: 'keyed',
              number: '4111111111111111',
              expiration_date: '11/20',
              cvc: '584',
              track_1: null,
              track_2: null,
              encrypted_track_1: null,
              encrypted_track_2: null,
              ksn: null,
              encrypted_data: null,
              cardholder_authentication: null,
              card_present: false
            },
            token: null
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Verna',
            last_name: 'Hegmann',
            company: 'Kub-Hansen',
            address_line_1: '77436 New Roadsville',
            address_line_2: null,
            city: 'South Hartmann',
            state: 'WA',
            postal_code: '60185',
            country: 'US',
            phone: '6618798013',
            fax: null,
            email: 'mikaylabeer@kub.org'
          },
          shipping_address: {
            first_name: 'Ora',
            last_name: 'Cronin',
            company: 'Stanton, Macejkovic and Mraz',
            address_line_1: '87661 Curvehaven',
            address_line_2: null,
            city: 'Hermanton',
            state: 'FM',
            postal_code: '60185',
            country: 'US',
            phone: '1425142620',
            fax: null,
            email: 'bertkerluke@yost.name'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp2645t7lmfuaigbqg',
          user_id: 'brpp24k5t7lmfuaiga2g',
          user_name: 'rippin4767',
          merchant_id: 'brpp24k5t7lmfuaiga20',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'authorize',
          amount: 9173,
          base_amount: 18446744073708863000,
          amount_authorized: 9173,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 696620,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga4g',
          processor_type: 'tsys_sierra',
          processor_name: 'Nestor Smith',
          payment_method: 'card',
          payment_type: 'card',
          features: [
            'avs',
            'card_verification',
            'levelii',
            'fake_response',
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 59,
          tax_exempt: false,
          shipping_amount: 7,
          surcharge: 0,
          discount_amount: 0,
          currency: 'usd',
          description: 'Keffiyeh street kickstarter.',
          order_id: 'Katrine',
          po_number: 'Hildegard',
          ip_address: '232.182.219.16',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: 'brpp2645t7lmfuaigbu0',
          customer_payment_type: 'card',
          customer_payment_ID: 'brpp2645t7lmfuaigbtg',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            card: {
              id: 'brpp2645t7lmfuaigbr0',
              card_type: 'visa',
              first_six: '411111',
              last_four: '1111',
              masked_card: '411111******1111',
              expiration_date: '11/20',
              response: 'approved',
              response_code: 100,
              auth_code: 'TAS000',
              processor_response_code: '00',
              processor_response_text: 'APPROVAL TAS000 ',
              processor_transaction_id: '000000000000000',
              processor_type: 'tsys_sierra',
              processor_id: 'brpp24s5t7lmfuaiga4g',
              bin_type: '',
              type: 'credit',
              avs_response_code: 'M',
              cvv_response_code: 'M',
              processor_specific: null,
              created_at: '2020-06-24T17:44:56.037945786Z',
              updated_at: '2020-06-24T17:44:56.046636619Z'
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'authorized',
          response: 'approved',
          response_code: 100,
          billing_address: {
            first_name: 'Verna',
            last_name: 'Hegmann',
            company: 'Kub-Hansen',
            address_line_1: '77436 New Roadsville',
            address_line_2: '',
            city: 'South Hartmann',
            state: 'WA',
            postal_code: '60185',
            country: 'US',
            phone: '6618798013',
            fax: '',
            email: 'mikaylabeer@kub.org'
          },
          shipping_address: {
            first_name: 'Ora',
            last_name: 'Cronin',
            company: 'Stanton, Macejkovic and Mraz',
            address_line_1: '87661 Curvehaven',
            address_line_2: '',
            city: 'Hermanton',
            state: 'FM',
            postal_code: '60185',
            country: 'US',
            phone: '1425142620',
            fax: '',
            email: 'bertkerluke@yost.name'
          },
          created_at: '2020-06-24T17:44:56.03244502Z',
          updated_at: '2020-06-24T17:44:56.049835946Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: 'TransactionCreateAuth failed, amounts are different',
        measurement: '35.60571ms',
        status_code: 200
      }
    ],
    stage_9: [
      {
        error: null,
        endpoint: 'POST http://localhost:8001/api/transaction',
        request: {
          idempotency_key: null,
          idempotency_time: null,
          type: 'sale',
          tax_exempt: false,
          currency: 'PHP',
          description: '3 wolf moon 8-bit sriracha.',
          order_id: 'Multi-lateral',
          po_number: 'utilisation',
          ip_address: '33.128.107.59',
          email_receipt: false,
          email_address: '',
          processor_id: null,
          allow_partial: null,
          create_vault_record: true,
          vendor_id: null,
          amount: 7357,
          tax_amount: 53,
          shipping_amount: 39,
          surcharge: null,
          discount_amount: null,
          national_tax_amount: null,
          duty_amount: null,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          payment_adjustment: null,
          additional_amounts: null,
          payment_method: {
            token: null,
            apm: {
              type: 'dragonpay',
              selling_point: null,
              sold_service: null,
              merchant_redirect_url: 'http://pe-test.dev.fluidpay.com:8127/readlog',
              locale: null,
              mobile_view: false,
              national_id: null,
              consumer_ref: null
            }
          },
          card_on_file_indicator: null,
          initiated_by: null,
          initial_transaction_id: null,
          stored_credential_indicator: null,
          billing_address: {
            first_name: 'Lemuel',
            last_name: 'Dare',
            company: 'Ferry Group',
            address_line_1: '117 New Missionmouth',
            address_line_2: null,
            city: 'Wolfchester',
            state: 'AZ',
            postal_code: '0185',
            country: 'PH',
            phone: '1080279882',
            fax: null,
            email: 'annefranecki@kshlerin.com'
          },
          shipping_address: {
            first_name: 'Lorenz',
            last_name: 'Schmidt',
            company: 'Homenick-Parker',
            address_line_1: '21463 Port Shoalland',
            address_line_2: null,
            city: 'Joanieberg',
            state: 'NJ',
            postal_code: '60185',
            country: 'US',
            phone: '2124268859',
            fax: null,
            email: 'bernardkuphal@walker.org'
          },
          processor_specific: null,
          custom_fields: null,
          group_name: '',
          descriptor: null,
          line_items: null,
          fingerprint: null,
          bypass_rule_engine: false,
          billing_method: ''
        },
        response: {
          id: 'brpp2645t7lmfuaigbv0',
          user_id: 'brpp24s5t7lmfuaiga60',
          user_name: 'walsh4936',
          merchant_id: 'brpp24s5t7lmfuaiga5g',
          idempotency_key: '',
          idempotency_time: 0,
          type: 'sale',
          amount: 7357,
          base_amount: 18446744073709404000,
          amount_authorized: 0,
          amount_captured: 0,
          amount_settled: 0,
          amount_refunded: 0,
          payment_adjustment: 153840,
          tip_amount: 0,
          settlement_batch_id: '',
          processor_id: 'brpp24s5t7lmfuaiga80',
          processor_type: 'mgiapm',
          processor_name: 'Ivy Welch',
          payment_method: 'apm',
          payment_type: 'dragonpay',
          features: [
            'card_on_file'
          ],
          national_tax_amount: 0,
          duty_amount: 0,
          ship_from_postal_code: '',
          summary_commodity_code: '',
          merchant_vat_registration_number: '',
          customer_vat_registration_number: '',
          tax_amount: 53,
          tax_exempt: false,
          shipping_amount: 39,
          surcharge: 0,
          discount_amount: 0,
          currency: 'php',
          description: '3 wolf moon 8-bit sriracha.',
          order_id: 'Multi-lateral',
          po_number: 'utilisation',
          ip_address: '33.128.107.59',
          transaction_source: 'api',
          email_receipt: false,
          email_address: '',
          customer_id: '',
          customer_payment_type: '',
          customer_payment_ID: '',
          subscription_id: '',
          referenced_transaction_id: '',
          response_body: {
            apm: {
              status: 'pending',
              processor_transaction_id: '690977008',
              transaction_id: 'brpp2645t7lmfuaigbv0',
              funding_status: 'not_expected',
              redirect_url: 'http://localhost:8080//api/redirect/apm/brpp2645t7lmfuaigbvg',
              channel: 'testchannel',
              tag: 'dragonpay',
              document_code: ''
            }
          },
          custom_fields: {},
          line_items: null,
          status: 'pending',
          response: 'pending',
          response_code: 99,
          billing_address: {
            first_name: 'Lemuel',
            last_name: 'Dare',
            company: 'Ferry Group',
            address_line_1: '117 New Missionmouth',
            address_line_2: '',
            city: 'Wolfchester',
            state: 'AZ',
            postal_code: '0185',
            country: 'PH',
            phone: '1080279882',
            fax: '',
            email: 'annefranecki@kshlerin.com'
          },
          shipping_address: {
            first_name: 'Lorenz',
            last_name: 'Schmidt',
            company: 'Homenick-Parker',
            address_line_1: '21463 Port Shoalland',
            address_line_2: '',
            city: 'Joanieberg',
            state: 'NJ',
            postal_code: '60185',
            country: 'US',
            phone: '2124268859',
            fax: '',
            email: 'bernardkuphal@walker.org'
          },
          created_at: '2020-06-24T17:44:56.068639111Z',
          updated_at: '2020-06-24T17:44:56.424253815Z',
          captured_at: null,
          settled_at: null
        },
        failed_message: '',
        measurement: '365.71839ms',
        status_code: 200
      }
    ]
  }

}
